### ISSUE TITLE
User can sign-up

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign-up to create an account
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can create an account by entering their personal details. They will then be directed to entering their interests so that related posts will eventually be seen in their feed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 40 52 AM](https://user-images.githubusercontent.com/99566488/171041992-f3d24fcd-9ef7-4f9a-83cd-a1f3489d9f4f.png)
![Screen Shot 2022-05-30 at 11 02 53 AM](https://user-images.githubusercontent.com/99566488/171042224-f02b3893-9fa0-40da-be10-6f57373bbc04.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Require authorization middleware
- [x] Create a POST server route for sign-up
- [x] test with HTTPie
- [x] create a hash route for sign-up
- [x] create layout for the sign-up form
- [x] Test front end functionality 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
