### ISSUE TITLE
User can comment on a post

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can comment on a post
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can comment on a post
- pressing/clicking the comment
  bubble will display a modal
- comment field is required to post
- the form resets after posting

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 42 23 AM](https://user-images.githubusercontent.com/99566488/171045198-b17fcf6c-e9be-42a4-9f52-56dfb2214f75.png)
![Screen Shot 2022-05-30 at 10 48 11 AM](https://user-images.githubusercontent.com/99566488/171045212-1883bf4c-50af-4a35-93a5-0a5e23dbec72.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a POST server route to insert a comment into the comments table
- [x] Test route with HTTPie
- [x] Add a comment button to the posts view
- [x] Add a modal for the comment form
- [x] Ensure the modal appears upon clicking the comment icon
- [x] Make sure the styling looks good on both mobile and desktop
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
