### ISSUE TITLE
User can view comments

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view comments
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view comment 
- after posting the user will be 
  sent back to the post 
- the comments will be displayed 
  newest to oldest
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 42 35 AM](https://user-images.githubusercontent.com/99566488/171045331-6a2458e2-7470-461c-b923-c7c53b3fae7d.png)
![Screen Shot 2022-05-30 at 10 48 20 AM](https://user-images.githubusercontent.com/99566488/171045350-b3a27ca3-2f20-40ee-b1c6-b2779799533c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add dummy comments to db for a post
- [x] Create a GET server route to view all comments on a post 
- [x] Test route with HTTPie
- [x] Create the layout for the comments
- [x] Add dummy content to layout
- [x] Make sure the styling looks good on both mobile and desktop
- [x] Ensure the comments render correctly
- [x] Remove dummy layout content
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
