### ISSUE TITLE
User can sign-in

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign into the app

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The use will enter their user name and password to log in

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 41 00 AM](https://user-images.githubusercontent.com/99566488/171042509-58b4646e-4810-4ec0-9e5b-67d57bb523de.png)
![Screen Shot 2022-05-30 at 11 03 19 AM](https://user-images.githubusercontent.com/99566488/171042559-09eb3165-0f3e-4379-899c-65b6cad87e40.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Require jsonwebtoken
- [x] Create a POST server route for sign-in
- [x] use argon2 to verify the password and hashpassword
- [x] use jwt.sign to create a json web token for the user
- [x] test with HTTPie
- [x] create a hash route for sign-up
- [x] import jwtDecode
- [x] Utilize context to share properties and methods to other components
- [x] Update Auth to conditionally render the sign in form and styling
- [x] Update Auth to render the sign in form after submitting the sign-up form
- [x] create a redirect component to direct the user to their feed if they are signed in
- [x] update the app to have a sign-in method
- [x] in the sign-in method set the jwt in the users local storage
- [x] update the componentDidMount method to check local storage for a web token
- [x] update componentDidMount to decode the web token to parse the user
- [x] update the state with the users info
- [x] Test front end functionality 
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
