### ISSUE TITLE
Design Update: feed image size based on likes

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#22]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User-can-view-feed

## 📐 Plan

> ##### Summary of the technical approach to be taken.

display feed images size based on number of likes

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

![Screen Shot 2022-05-30 at 10 38 28 AM](https://user-images.githubusercontent.com/99566488/172495697-e645b667-6ae9-4096-9faf-b6463e9436eb.png)
![Screen Shot 2022-05-30 at 10 46 12 AM](https://user-images.githubusercontent.com/99566488/172495731-37543e84-62d2-4fa2-9372-00a3c2638003.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] update the backend code to select and count the number of likes per post
- [x] test with HTTPie
- [x] add condition to .map to set px height and width according to like count
- [x] check to see if posts  images are being displayed correctly
