### ISSUE TITLE
User can view their profile

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their profile
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user has logged in, they will be directed to their profile page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 11 01 AM](https://user-images.githubusercontent.com/99566488/171043140-f35155d0-f049-4d37-acfc-cfe55db905ba.png)
![Screen Shot 2022-05-30 at 10 44 36 AM](https://user-images.githubusercontent.com/99566488/171043167-f9cc95ed-138f-485c-9dff-07e9868e302f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a hash route for the profile
- [x] Create a layout for the profile view
- [x] Check to see if the styling looks good on mobile and desktop
- [x] Use context to get the users username
- [x] Remove any unnecessary styling
- [x] Check for bugs
- [x] Test in private browser
