### ISSUE TITLE
Bug: Margins / Navbar positioning

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#47]
#### Desired Behavior

> ##### The Navbar and Margin on desktop (feed/post view) should remain the same with the profile and create post view

#### Actual Behavior

> ##### The navbar and margin position changes on feed and post view 

#### Steps to Reproduce

> ##### To trigger the bug, you must change between feed/postDetails and createPost/profile pages

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.
  - [ ] Compare affected pages with unaffected pages to pinpoint the problem
  - [ ] adjust styling according to unaffected pages
  - [ ] ensure mobile styling is unaffected 
  - [ ] remove any unnecessary styling
