### ISSUE TITLE
User can sign-out

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign-out
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can sign-out of the application by clicking the sign-out button. They will be directed to the sign-up/login page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 17 17 AM](https://user-images.githubusercontent.com/99566488/171043654-ab540c76-f030-4a9d-ae50-dfe75af7ce74.png)
![Screen Shot 2022-05-30 at 10 45 33 AM](https://user-images.githubusercontent.com/99566488/171043668-7e1a42fa-baca-430d-95df-940c30c28af2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create handleSignOut method
- [x] Destructure handleSignOut from this and assign to context
- [x] Add a sign-out button
- [x] Ensure the user is redirected to the home page when the sign out button is clicked
- [x] check to see that the user's token is cleared from local storage
