### ISSUE TITLE
User can view their feed

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their feed
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can view their feed. The feed will initially be all posts.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 38 28 AM](https://user-images.githubusercontent.com/99566488/171043865-b7fbb100-2e5e-4da1-8307-a1f5cccc9fba.png)
![Screen Shot 2022-05-30 at 10 46 12 AM](https://user-images.githubusercontent.com/99566488/171043882-93e39c64-46d4-4f6b-b620-3cb36b07f557.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add dummy posts and likes to db
- [x] Create a GET server route to get posts based on user likes
- [x] Test route with HTTPie
- [x] Create the layout for the posts in the feed with dummy data
- [x] Make sure the styling looks good on both mobile and desktop
- [x] Build the front end functionality for the feed
- [x] Test to make sure the posts are displayed correctly
- [x] Remove dummy data
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
