### ISSUE TITLE
User can create a post

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a post
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create a post
- can upload a picture
- submitting the form resets the form
- the focused input has a blue outline
- all inputs are required

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 11 53 58 AM](https://user-images.githubusercontent.com/99566488/171047513-32a35e63-e8f5-414c-b75d-eb7d912fd6c7.png)
![Screen Shot 2022-05-30 at 11 53 49 AM](https://user-images.githubusercontent.com/99566488/171047520-be956495-d55d-4192-a07b-34ac4d6c05b9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a form for creating a new post
- [x] Ensure that the form looks nice on both mobile and desktop
- [x] Make all inputs required
- [x] On submit update the database with the users inputs
- [x] reset the form
- [x] Verify the user inputs are stored in the database
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
