### ISSUE TITLE
User can view their post in their feed

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their post in their feed
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User view their post in their feed
- user post displays in top left
- submitting the form resets the form
- posting the post automatically
  shows the feed

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 41 49 AM](https://user-images.githubusercontent.com/99566488/171044566-f2747655-c684-4116-8851-6452faa4b554.png)
![Screen Shot 2022-05-30 at 10 47 41 AM](https://user-images.githubusercontent.com/99566488/171044597-1833c590-b6d6-41da-8b5d-3a7a5e108b2d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a GET server route to select a specific postId
- [x] Test route with HTTPie
- [x] create a hash route for the post view 
- [x] Create the layout for the post with react element dummy data
- [x] Make sure the styling looks good on both mobile and desktop
- [x] render post content when a picture in feed is clicked
- [x] Test to make sure the post is displayed correctly
- [x] Remove react element dummy data
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
