### ISSUE TITLE
User can like a post

### ISSUE THREAD

**Issue by NickANewton** [NickANewton/bubble#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like a post
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can like a post
- pressing/clicking the heart will
   like the post 
- heart backgound fills blue

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 10 42 03 AM](https://user-images.githubusercontent.com/99566488/171044892-af9fc9f3-bcaf-4dfa-a200-4a902777d14c.png)
![Screen Shot 2022-05-30 at 10 47 51 AM](https://user-images.githubusercontent.com/99566488/171044917-b939400b-0f0e-4e9f-b38a-ce431880c1aa.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a GET server route to check if the postId and userId are already in the likes table
- [x] Test route with HTTPie
- [x] Create a POST server route to insert the postId and userId into the likes table
- [x] Test route with HTTPie
- [x] Create the layout for the like button
- [x] Make sure the styling looks good on both mobile and desktop
- [x] Update the heart icon's color depending on whether or not the post has been liked
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary
- [x] Test all functionality again in a private browsing session
- [x] Fix all errors
